require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrepodsController do

  # This should return the minimal set of attributes required to create a valid
  # Prepod. As you add validations to Prepod, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all prepods as @prepods" do
      prepod = Prepod.create! valid_attributes
      get :index
      assigns(:prepods).should eq([prepod])
    end
  end

  describe "GET show" do
    it "assigns the requested prepod as @prepod" do
      prepod = Prepod.create! valid_attributes
      get :show, :id => prepod.id.to_s
      assigns(:prepod).should eq(prepod)
    end
  end

  describe "GET new" do
    it "assigns a new prepod as @prepod" do
      get :new
      assigns(:prepod).should be_a_new(Prepod)
    end
  end

  describe "GET edit" do
    it "assigns the requested prepod as @prepod" do
      prepod = Prepod.create! valid_attributes
      get :edit, :id => prepod.id.to_s
      assigns(:prepod).should eq(prepod)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prepod" do
        expect {
          post :create, :prepod => valid_attributes
        }.to change(Prepod, :count).by(1)
      end

      it "assigns a newly created prepod as @prepod" do
        post :create, :prepod => valid_attributes
        assigns(:prepod).should be_a(Prepod)
        assigns(:prepod).should be_persisted
      end

      it "redirects to the created prepod" do
        post :create, :prepod => valid_attributes
        response.should redirect_to(Prepod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prepod as @prepod" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prepod.any_instance.stub(:save).and_return(false)
        post :create, :prepod => {}
        assigns(:prepod).should be_a_new(Prepod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prepod.any_instance.stub(:save).and_return(false)
        post :create, :prepod => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prepod" do
        prepod = Prepod.create! valid_attributes
        # Assuming there are no other prepods in the database, this
        # specifies that the Prepod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Prepod.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => prepod.id, :prepod => {'these' => 'params'}
      end

      it "assigns the requested prepod as @prepod" do
        prepod = Prepod.create! valid_attributes
        put :update, :id => prepod.id, :prepod => valid_attributes
        assigns(:prepod).should eq(prepod)
      end

      it "redirects to the prepod" do
        prepod = Prepod.create! valid_attributes
        put :update, :id => prepod.id, :prepod => valid_attributes
        response.should redirect_to(prepod)
      end
    end

    describe "with invalid params" do
      it "assigns the prepod as @prepod" do
        prepod = Prepod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prepod.any_instance.stub(:save).and_return(false)
        put :update, :id => prepod.id.to_s, :prepod => {}
        assigns(:prepod).should eq(prepod)
      end

      it "re-renders the 'edit' template" do
        prepod = Prepod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prepod.any_instance.stub(:save).and_return(false)
        put :update, :id => prepod.id.to_s, :prepod => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prepod" do
      prepod = Prepod.create! valid_attributes
      expect {
        delete :destroy, :id => prepod.id.to_s
      }.to change(Prepod, :count).by(-1)
    end

    it "redirects to the prepods list" do
      prepod = Prepod.create! valid_attributes
      delete :destroy, :id => prepod.id.to_s
      response.should redirect_to(prepods_url)
    end
  end

end
