require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicationTypesController do

  # This should return the minimal set of attributes required to create a valid
  # PublicationType. As you add validations to PublicationType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all publication_types as @publication_types" do
      publication_type = PublicationType.create! valid_attributes
      get :index
      assigns(:publication_types).should eq([publication_type])
    end
  end

  describe "GET show" do
    it "assigns the requested publication_type as @publication_type" do
      publication_type = PublicationType.create! valid_attributes
      get :show, :id => publication_type.id.to_s
      assigns(:publication_type).should eq(publication_type)
    end
  end

  describe "GET new" do
    it "assigns a new publication_type as @publication_type" do
      get :new
      assigns(:publication_type).should be_a_new(PublicationType)
    end
  end

  describe "GET edit" do
    it "assigns the requested publication_type as @publication_type" do
      publication_type = PublicationType.create! valid_attributes
      get :edit, :id => publication_type.id.to_s
      assigns(:publication_type).should eq(publication_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PublicationType" do
        expect {
          post :create, :publication_type => valid_attributes
        }.to change(PublicationType, :count).by(1)
      end

      it "assigns a newly created publication_type as @publication_type" do
        post :create, :publication_type => valid_attributes
        assigns(:publication_type).should be_a(PublicationType)
        assigns(:publication_type).should be_persisted
      end

      it "redirects to the created publication_type" do
        post :create, :publication_type => valid_attributes
        response.should redirect_to(PublicationType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publication_type as @publication_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationType.any_instance.stub(:save).and_return(false)
        post :create, :publication_type => {}
        assigns(:publication_type).should be_a_new(PublicationType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationType.any_instance.stub(:save).and_return(false)
        post :create, :publication_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested publication_type" do
        publication_type = PublicationType.create! valid_attributes
        # Assuming there are no other publication_types in the database, this
        # specifies that the PublicationType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PublicationType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => publication_type.id, :publication_type => {'these' => 'params'}
      end

      it "assigns the requested publication_type as @publication_type" do
        publication_type = PublicationType.create! valid_attributes
        put :update, :id => publication_type.id, :publication_type => valid_attributes
        assigns(:publication_type).should eq(publication_type)
      end

      it "redirects to the publication_type" do
        publication_type = PublicationType.create! valid_attributes
        put :update, :id => publication_type.id, :publication_type => valid_attributes
        response.should redirect_to(publication_type)
      end
    end

    describe "with invalid params" do
      it "assigns the publication_type as @publication_type" do
        publication_type = PublicationType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationType.any_instance.stub(:save).and_return(false)
        put :update, :id => publication_type.id.to_s, :publication_type => {}
        assigns(:publication_type).should eq(publication_type)
      end

      it "re-renders the 'edit' template" do
        publication_type = PublicationType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationType.any_instance.stub(:save).and_return(false)
        put :update, :id => publication_type.id.to_s, :publication_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publication_type" do
      publication_type = PublicationType.create! valid_attributes
      expect {
        delete :destroy, :id => publication_type.id.to_s
      }.to change(PublicationType, :count).by(-1)
    end

    it "redirects to the publication_types list" do
      publication_type = PublicationType.create! valid_attributes
      delete :destroy, :id => publication_type.id.to_s
      response.should redirect_to(publication_types_url)
    end
  end

end
