require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicationsTypesController do

  # This should return the minimal set of attributes required to create a valid
  # PublicationsType. As you add validations to PublicationsType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all publications_types as @publications_types" do
      publications_type = PublicationsType.create! valid_attributes
      get :index
      assigns(:publications_types).should eq([publications_type])
    end
  end

  describe "GET show" do
    it "assigns the requested publications_type as @publications_type" do
      publications_type = PublicationsType.create! valid_attributes
      get :show, :id => publications_type.id.to_s
      assigns(:publications_type).should eq(publications_type)
    end
  end

  describe "GET new" do
    it "assigns a new publications_type as @publications_type" do
      get :new
      assigns(:publications_type).should be_a_new(PublicationsType)
    end
  end

  describe "GET edit" do
    it "assigns the requested publications_type as @publications_type" do
      publications_type = PublicationsType.create! valid_attributes
      get :edit, :id => publications_type.id.to_s
      assigns(:publications_type).should eq(publications_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PublicationsType" do
        expect {
          post :create, :publications_type => valid_attributes
        }.to change(PublicationsType, :count).by(1)
      end

      it "assigns a newly created publications_type as @publications_type" do
        post :create, :publications_type => valid_attributes
        assigns(:publications_type).should be_a(PublicationsType)
        assigns(:publications_type).should be_persisted
      end

      it "redirects to the created publications_type" do
        post :create, :publications_type => valid_attributes
        response.should redirect_to(PublicationsType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publications_type as @publications_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationsType.any_instance.stub(:save).and_return(false)
        post :create, :publications_type => {}
        assigns(:publications_type).should be_a_new(PublicationsType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationsType.any_instance.stub(:save).and_return(false)
        post :create, :publications_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested publications_type" do
        publications_type = PublicationsType.create! valid_attributes
        # Assuming there are no other publications_types in the database, this
        # specifies that the PublicationsType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PublicationsType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => publications_type.id, :publications_type => {'these' => 'params'}
      end

      it "assigns the requested publications_type as @publications_type" do
        publications_type = PublicationsType.create! valid_attributes
        put :update, :id => publications_type.id, :publications_type => valid_attributes
        assigns(:publications_type).should eq(publications_type)
      end

      it "redirects to the publications_type" do
        publications_type = PublicationsType.create! valid_attributes
        put :update, :id => publications_type.id, :publications_type => valid_attributes
        response.should redirect_to(publications_type)
      end
    end

    describe "with invalid params" do
      it "assigns the publications_type as @publications_type" do
        publications_type = PublicationsType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationsType.any_instance.stub(:save).and_return(false)
        put :update, :id => publications_type.id.to_s, :publications_type => {}
        assigns(:publications_type).should eq(publications_type)
      end

      it "re-renders the 'edit' template" do
        publications_type = PublicationsType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationsType.any_instance.stub(:save).and_return(false)
        put :update, :id => publications_type.id.to_s, :publications_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publications_type" do
      publications_type = PublicationsType.create! valid_attributes
      expect {
        delete :destroy, :id => publications_type.id.to_s
      }.to change(PublicationsType, :count).by(-1)
    end

    it "redirects to the publications_types list" do
      publications_type = PublicationsType.create! valid_attributes
      delete :destroy, :id => publications_type.id.to_s
      response.should redirect_to(publications_types_url)
    end
  end

end
