require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicationCatsController do

  # This should return the minimal set of attributes required to create a valid
  # PublicationCat. As you add validations to PublicationCat, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all publication_cats as @publication_cats" do
      publication_cat = PublicationCat.create! valid_attributes
      get :index
      assigns(:publication_cats).should eq([publication_cat])
    end
  end

  describe "GET show" do
    it "assigns the requested publication_cat as @publication_cat" do
      publication_cat = PublicationCat.create! valid_attributes
      get :show, :id => publication_cat.id.to_s
      assigns(:publication_cat).should eq(publication_cat)
    end
  end

  describe "GET new" do
    it "assigns a new publication_cat as @publication_cat" do
      get :new
      assigns(:publication_cat).should be_a_new(PublicationCat)
    end
  end

  describe "GET edit" do
    it "assigns the requested publication_cat as @publication_cat" do
      publication_cat = PublicationCat.create! valid_attributes
      get :edit, :id => publication_cat.id.to_s
      assigns(:publication_cat).should eq(publication_cat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PublicationCat" do
        expect {
          post :create, :publication_cat => valid_attributes
        }.to change(PublicationCat, :count).by(1)
      end

      it "assigns a newly created publication_cat as @publication_cat" do
        post :create, :publication_cat => valid_attributes
        assigns(:publication_cat).should be_a(PublicationCat)
        assigns(:publication_cat).should be_persisted
      end

      it "redirects to the created publication_cat" do
        post :create, :publication_cat => valid_attributes
        response.should redirect_to(PublicationCat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publication_cat as @publication_cat" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationCat.any_instance.stub(:save).and_return(false)
        post :create, :publication_cat => {}
        assigns(:publication_cat).should be_a_new(PublicationCat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationCat.any_instance.stub(:save).and_return(false)
        post :create, :publication_cat => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested publication_cat" do
        publication_cat = PublicationCat.create! valid_attributes
        # Assuming there are no other publication_cats in the database, this
        # specifies that the PublicationCat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PublicationCat.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => publication_cat.id, :publication_cat => {'these' => 'params'}
      end

      it "assigns the requested publication_cat as @publication_cat" do
        publication_cat = PublicationCat.create! valid_attributes
        put :update, :id => publication_cat.id, :publication_cat => valid_attributes
        assigns(:publication_cat).should eq(publication_cat)
      end

      it "redirects to the publication_cat" do
        publication_cat = PublicationCat.create! valid_attributes
        put :update, :id => publication_cat.id, :publication_cat => valid_attributes
        response.should redirect_to(publication_cat)
      end
    end

    describe "with invalid params" do
      it "assigns the publication_cat as @publication_cat" do
        publication_cat = PublicationCat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationCat.any_instance.stub(:save).and_return(false)
        put :update, :id => publication_cat.id.to_s, :publication_cat => {}
        assigns(:publication_cat).should eq(publication_cat)
      end

      it "re-renders the 'edit' template" do
        publication_cat = PublicationCat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicationCat.any_instance.stub(:save).and_return(false)
        put :update, :id => publication_cat.id.to_s, :publication_cat => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publication_cat" do
      publication_cat = PublicationCat.create! valid_attributes
      expect {
        delete :destroy, :id => publication_cat.id.to_s
      }.to change(PublicationCat, :count).by(-1)
    end

    it "redirects to the publication_cats list" do
      publication_cat = PublicationCat.create! valid_attributes
      delete :destroy, :id => publication_cat.id.to_s
      response.should redirect_to(publication_cats_url)
    end
  end

end
