require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShedulesController do

  # This should return the minimal set of attributes required to create a valid
  # Shedule. As you add validations to Shedule, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all shedules as @shedules" do
      shedule = Shedule.create! valid_attributes
      get :index
      assigns(:shedules).should eq([shedule])
    end
  end

  describe "GET show" do
    it "assigns the requested shedule as @shedule" do
      shedule = Shedule.create! valid_attributes
      get :show, :id => shedule.id.to_s
      assigns(:shedule).should eq(shedule)
    end
  end

  describe "GET new" do
    it "assigns a new shedule as @shedule" do
      get :new
      assigns(:shedule).should be_a_new(Shedule)
    end
  end

  describe "GET edit" do
    it "assigns the requested shedule as @shedule" do
      shedule = Shedule.create! valid_attributes
      get :edit, :id => shedule.id.to_s
      assigns(:shedule).should eq(shedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shedule" do
        expect {
          post :create, :shedule => valid_attributes
        }.to change(Shedule, :count).by(1)
      end

      it "assigns a newly created shedule as @shedule" do
        post :create, :shedule => valid_attributes
        assigns(:shedule).should be_a(Shedule)
        assigns(:shedule).should be_persisted
      end

      it "redirects to the created shedule" do
        post :create, :shedule => valid_attributes
        response.should redirect_to(Shedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shedule as @shedule" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shedule.any_instance.stub(:save).and_return(false)
        post :create, :shedule => {}
        assigns(:shedule).should be_a_new(Shedule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shedule.any_instance.stub(:save).and_return(false)
        post :create, :shedule => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shedule" do
        shedule = Shedule.create! valid_attributes
        # Assuming there are no other shedules in the database, this
        # specifies that the Shedule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shedule.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => shedule.id, :shedule => {'these' => 'params'}
      end

      it "assigns the requested shedule as @shedule" do
        shedule = Shedule.create! valid_attributes
        put :update, :id => shedule.id, :shedule => valid_attributes
        assigns(:shedule).should eq(shedule)
      end

      it "redirects to the shedule" do
        shedule = Shedule.create! valid_attributes
        put :update, :id => shedule.id, :shedule => valid_attributes
        response.should redirect_to(shedule)
      end
    end

    describe "with invalid params" do
      it "assigns the shedule as @shedule" do
        shedule = Shedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shedule.any_instance.stub(:save).and_return(false)
        put :update, :id => shedule.id.to_s, :shedule => {}
        assigns(:shedule).should eq(shedule)
      end

      it "re-renders the 'edit' template" do
        shedule = Shedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shedule.any_instance.stub(:save).and_return(false)
        put :update, :id => shedule.id.to_s, :shedule => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shedule" do
      shedule = Shedule.create! valid_attributes
      expect {
        delete :destroy, :id => shedule.id.to_s
      }.to change(Shedule, :count).by(-1)
    end

    it "redirects to the shedules list" do
      shedule = Shedule.create! valid_attributes
      delete :destroy, :id => shedule.id.to_s
      response.should redirect_to(shedules_url)
    end
  end

end
